//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Communicator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Communicator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon2 {
            get {
                object obj = ResourceManager.GetObject("icon2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream messageSent {
            get {
                return ResourceManager.GetStream("messageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MS {
            get {
                object obj = ResourceManager.GetObject("MS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MW {
            get {
                object obj = ResourceManager.GetObject("MW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;chuj&apos;,&apos;chuja&apos;, &apos;chujek&apos;, &apos;chuju&apos;, &apos;chujem&apos;, &apos;chujnia&apos;,
        ///&apos;chujowy&apos;, &apos;chujowa&apos;, &apos;chujowe&apos;, &apos;cipa&apos;, &apos;cipę&apos;, &apos;cipe&apos;, &apos;cipą&apos;,
        ///&apos;cipie&apos;, &apos;dojebać&apos;,&apos;dojebac&apos;, &apos;dojebie&apos;, &apos;dojebał&apos;, &apos;dojebal&apos;,
        ///&apos;dojebała&apos;, &apos;dojebala&apos;, &apos;dojebałem&apos;, &apos;dojebalem&apos;, &apos;dojebałam&apos;,
        ///&apos;dojebalam&apos;, &apos;dojebię&apos;, &apos;dojebie&apos;, &apos;dopieprzać&apos;, &apos;dopieprzac&apos;,
        ///&apos;dopierdalać&apos;, &apos;dopierdalac&apos;, &apos;dopierdala&apos;, &apos;dopierdalał&apos;,
        ///&apos;dopierdalal&apos;, &apos;dopierdalała&apos;, &apos;dopierdalala&apos;, &apos;dopierdoli&apos;,
        ///&apos;dopierdolił&apos;, &apos;dopierdolil&apos;, &apos;dopierdolę&apos;, &apos;dopierdole&apos;, &apos;dopierdoli&apos;,
        ///&apos;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vulgarWords {
            get {
                return ResourceManager.GetString("vulgarWords", resourceCulture);
            }
        }
    }
}
